version: "3"

vars:
  PROGRAM: entra-phishing-detection

tasks:
  deps:
    cmds:
      - go mod tidy -v

  update:
    deps:
      - prompt-update
    cmds:
      - go get -u
      - go get -u tool
      - go mod tidy -v

  build:
    aliases: [default]
    deps: [deps]
    env:
      CGO_ENABLED: 0
    cmds:
      - go fmt ./...
      - go tool gofumpt -l -w .
      - go vet ./...
      - go fix ./...
      - go build -o {{.PROGRAM}}

  test:
    deps: [deps]
    env:
      CGO_ENABLED: 1
    cmds:
      - go test -race -cover ./...

  run:
    deps: [build]
    cmds:
      - ./{{.PROGRAM}} -debug -config config.json

  dev:
    deps: [build]
    cmds:
      - go tool air

  configcheck:
    deps: [build]
    cmds:
      - ./{{.PROGRAM}} -configcheck -config config.json

  lint:
    cmds:
      - golangci-lint run ./... --timeout=30m
      - go mod tidy

  lint-update:
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest

  tag:
    cmds:
      - git tag -a "${TAG}" -m "${TAG}"
      - git push origin "${TAG}"
    preconditions:
      - sh: '[[ -n "${TAG}" ]]'
        msg: "Please set the TAG environment variable"

  prompt-update:
    # https://daisyui.com/docs/editor/vscode/
    # https://github.com/github/awesome-copilot/tree/main/instructions
    cmds:
      - curl -sSfL https://daisyui.com/llms.txt --create-dirs -o .github/instructions/daisyui.instructions.md
      - curl -sSfL https://raw.githubusercontent.com/github/awesome-copilot/refs/heads/main/instructions/go.instructions.md --create-dirs -o .github/instructions/go.instructions.md
      - curl -sSfL https://github.com/github/awesome-copilot/raw/refs/heads/main/instructions/containerization-docker-best-practices.instructions.md --create-dirs -o .github/instructions/containerization-docker-best-practices.instructions.md
      - curl -sSfL https://github.com/github/awesome-copilot/raw/refs/heads/main/instructions/devops-core-principles.instructions.md --create-dirs -o .github/instructions/devops-core-principles.instructions.md
      - curl -sSfL https://github.com/github/awesome-copilot/raw/refs/heads/main/instructions/github-actions-ci-cd-best-practices.instructions.md --create-dirs -o .github/instructions/github-actions-ci-cd-best-practices.instructions.md
      - curl -sSfL https://github.com/github/awesome-copilot/raw/refs/heads/main/instructions/security-and-owasp.instructions.md --create-dirs -o .github/instructions/security-and-owasp.instructions.md
