apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "entra-phishing-detection.fullname" . }}
  labels:
    {{- include "entra-phishing-detection.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "entra-phishing-detection.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "entra-phishing-detection.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "entra-phishing-detection.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/app"]
          args: ["-config", "/config/config.json"]
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: metrics
              containerPort: 8001
              protocol: TCP
            - name: pprof
              containerPort: 8002
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /{{ .Values.configFile.pathHealth }}
              port: http
              httpHeaders:
                - name: {{ .Values.configFile.secretKeyHeaderName }}
                  value: {{ .Values.configFile.secretKeyHeaderValue }}
          readinessProbe:
            httpGet:
              path: /{{ .Values.configFile.pathHealth }}
              port: http
              httpHeaders:
                - name: {{ .Values.configFile.secretKeyHeaderName }}
                  value: {{ .Values.configFile.secretKeyHeaderValue }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: log
              mountPath: /var/log/entra
            - name: config
              mountPath: /config
              readOnly: true
        {{- if .Values.fluentBit.enabled }}
        - name: {{ .Chart.Name }}-fluentbit
          image: "{{ .Values.fluentBit.image.repository }}:{{ .Values.fluentBit.image.tag }}"
          imagePullPolicy: {{ .Values.fluentBit.image.pullPolicy }}
          command: ["/fluent-bit/bin/fluent-bit"]
          args: ["-c", "/config/fluentbit.yml"]
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          {{- with .Values.fluentBit.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: log
              mountPath: {{ .Values.pvc.logfilePath }}
            - name: fluentbit-config
              mountPath: /config
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "entra-phishing-detection.fullname" . }}
            items:
              - key: "config.json"
                path: "config.json"
        {{- if .Values.fluentBit.enabled }}
        - name: log
          persistentVolumeClaim:
            claimName: {{ include "entra-phishing-detection.fullname" . }}
        - name: fluentbit-config
          configMap:
            name: {{ include "entra-phishing-detection.fullname" . }}
            items:
              - key: "fluentbit.yml"
                path: "fluentbit.yml"
        {{- end }}
