{{- if .Values.route.enabled -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "entra-phishing-detection.fullname" . }}
  labels:
    {{- include "entra-phishing-detection.labels" . | nindent 4 }}
  annotations:
    # https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/networking/configuring-routes#nw-disabling-hsts_route-configuration
    haproxy.router.openshift.io/disable_cookies: "true"
spec:
  host: {{ .Values.route.hostName }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "entra-phishing-detection.fullname" . }}
{{- end }}
